import Head from "next/head"
import { FormControl, FormErrorMessage, FormHelperText, FormLabel } from '@components/libs/FormControl/index';
import { Input } from '@components/libs/Input/index';
import Button from '@components/libs/Button/index';
import { FcGoogle } from 'react-icons/fc';
import NextImage from '@components/nextImage';
import { ProgressBar, ProgressBarCaption } from '@components/libs/Progress Bar';
import Switch from '@components/libs/Switch';
import { useState } from 'react';
import { Skeleton, SkeletonCircle, SkeletonImage, SkeletonText } from '@components/libs/Skeleton';
import { classNames, colorsFunction, radiusFunction, spacingFunction } from '@functions/index';
import { LoadingBar } from "@components/libs/LoadingBar";
import Link from "next/link";
import { useRouter } from "next/router";

export default function Home() {
    const [update, setUpdate] = useState(0)
    const onUpdate = () => {
        setUpdate(update + 10)
    };
    const router = useRouter();
    // console.log(router.query.id)
    // console.log(update)
    // console.log(colorsFunction("aquamarine", "text"))

  return (
    <div className="w-screen h-screen flex mx-3 mt-3">
      <Head>
        <title>home </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        {/* <FormControl>
            <FormLabel label="goods" />
            <Input size="sm" isInvalid className="" />
            <FormHelperText>try tomorrow</FormHelperText>
            <FormErrorMessage>Go to hell</FormErrorMessage>
        </FormControl>
        <Input size="sm" clearable />
        <span className=" peer-aria-invalid:bg-blue-500">Go to hell</span> */}
            {/* <FormErrorMessage className="peer-invalid:inline-flex">Go to hell</FormErrorMessage> */}
        {/* <Button 
                // isDisabled
                colorScheme="none" 
                iconSpacing="md" 
                isFullWidth 
                className="text-pen-c font-semibold drop-shadow-none border-pen-e" 
                rightIcon={<FcGoogle size="20px" />} 
                variant="outline" 
                // onClick={handleLgnGoogle} 
            > 
                Google 
        </Button> */}
        
        {/* <NextImage 
          src="/"
          width={600}
          height={150}
          // alt="unknown"
        /> */}
         <Link href="/">index page</Link>

            <ProgressBar 
              colorScheme="blue" 
              hasStripe 
              shadow="lg"
              size="xs"
              // shimmer
              // ringWidth="sm"
              // animatedStripes 
              // value={60} 
              >
            </ProgressBar>
            {/* <LoadingBar loadingState="done" /> */}
        
    
    </div>
  )

}
