import Head from "next/head";
import Image from "next/image";
import { RiSunLine } from "react-icons/ri";
import Button from "@components/libs/Button";
import {
  Drawer,
  DrawerCloseButton,
  DrawerContent,
  DrawerHeader,
  DrawerBody,
  DrawerFooter,
} from "@components/libs/Drawer";
import {
  Modal,
  ModalContent,
  ModalHeader,
  ModalBody,
  ModalFooter,
  ModalCloseButton,
} from "@components/libs/Modal";
import { CgSpinner } from "react-icons/cg";
import IconButton from "@components/libs/Button/IconButton";
import { useToggle } from "@hooks/useToggle";
import React, {
  useEffect,
  useRef,
  useCallback,
  createRef,
  useState,
} from "react";
import Portal from "@components/libs/Portal";
import { ListItem, List } from "@components/libs/List";
import { Menu, MenuButton, MenuList } from "@components/libs/Menu";
import { Example } from "@components/custom";
import { Divider } from "@components/libs/Divider";
import {
  Input,
  InputRightAddOn,
  InputLeftAddOn,
  InputRightButton,
  InputLeftButton,
  InputRightElement,
  InputLeftElement,
} from "@components/libs/Input";
import { InputGroup } from "@components/libs/Input/InputGroup";
import { ButtonGroup } from "@components/libs/Button/ButtonGroup";
import { ButtonBase } from "@components/libs/Button/ButtonBase";
import Badge from "@components/libs/Badge";
import { Checkbox } from "@components/libs/CheckBox";
import { CheckboxGroup } from "@components/libs/CheckBox/CheckBoxGroup";
import { Radio } from "@components/libs/Radio";
import { RadioGroup } from "@components/libs/Radio/RadioGroup";
import { InputBase } from "@components/libs/Input/InputBase";
import { Overlay } from "@components/libs/Overlay";
import {
  Alert,
  AlertDescription,
  AlertIcon,
  AlertTitle,
} from "@components/libs/Alert";
import Avatar from "@components/libs/Avatar";
import TextArea from "@components/libs/TextArea";
import Link from "next/link";
import { useRouter } from "next/router";
// import FormGroup from '@components/formGroup';

export default function Home() {
  // const [open, toggle] = useToggle();
  const router = useRouter()
  const [value, setValue] = useState<string>();
  const handleClick = () => {
    // toggle()
    !open ? window.history.pushState({open: true}, "", "/create-krowd") : window.history.go(-1);
  };
  // console.log(open)
  return (
    <div className="w-screen h-screen flex mx-auto pt-5 ">
      <Head>
        <title>mega day</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Button variant="ghost" aria-haspopup="dialog" size="md" onClick={handleClick}>
        open custom modal
      </Button>
      <Modal scrollBehaviour="inside" open={open} toggle={handleClick}>
      <Overlay />
      <ModalContent >
      <ModalCloseButton />
        <ModalHeader> modal Title</ModalHeader>
        <ModalBody>
          dolor sit amet, consectetur adipis lorem ipsum dolor sit amet, consectetur adipis lorem ipsum dolor sit amet, consectetur adipis lorem ipsum dolor sit amet, consectetur adipis lorem ipsum dolor sit amet, consectetur adipis lorem ipsum dolor sit amet, consecteconsectetur adipis pis lorem ipsum dolor sit amet, consectetur adipis lorem ipsum dolor sit amet, consectetur adipis lorem ipsum dolor sit amet, consecteconsectetur adipispis lorem ipsum dolor sit amet, consectetur adipis lorem ipsum dolor sit amet, consectetur adipis lorem ipsum dolor sit amet, consecteconsectetur adipispis lorem ipsum dolor sit amet, consectetur adipis lorem ipsum dolor sit amet, consectetur adipis lorem ipsum dolor sit amet, consecteconsectetur adipispis lorem ipsum dolor sit amet, consectetur adipis lorem ipsum dolor sit amet, consectetur adipis lorem ipsum dolor sit amet, consecteconsectetur adipispis lorem ipsum dolor sit amet, consectetur adipis lorem ipsum dolor sit amet, consectetur adipis lorem ipsum dolor sit amet, consecteconsectetur adipispis lorem ipsum dolor sit amet, consectetur adipis lorem ipsum dolor sit amet, consectetur adipis lorem ipsum dolor sit amet, consecteconsectetur adipispis lorem ipsum dolor sit amet, consectetur adipis lorem ipsum dolor sit amet, consectetur adipis lorem ipsum dolor sit amet, consecteconsectetur adipispis lorem ipsum dolor sit amet, consectetur adipis lorem ipsum dolor sit amet, consectetur adipis lorem ipsum dolor sit amet, consecteconsectetur adipispis lorem ipsum dolor sit amet, consectetur adipis lorem ipsum dolor sit amet, consectetur adipis lorem ipsum dolor sit amet, consecteconsectetur adipispis lorem ipsum dolor sit amet, consectetur adipis lorem ipsum dolor sit amet, consectetur adipis lorem ipsum dolor sit amet, consecteconsectetur adipis
          <label htmlFor="name">
          <input id="name" name="name" type="text" placeholder="name" className="input" />
          </label>
        </ModalBody>
        <ModalFooter>
          <Button size="md" variant="outline"  >click me</Button>
        </ModalFooter>
      </ModalContent>
    </Modal>
    </div>
  );
}
